### ISSUE TITLE
graphql-middleware is currently unmaintained

### ISSUE THREAD

**Issue by spathon** [maticzav/graphql-shield#1001]
# Question about GraphQL Shield

[graphql-middleware](https://github.com/prisma-labs/graphql-middleware) is no longer maintained. 
They have just added a *WARNING: This project is currently unmaintained* notice in the top of their readme and last update was over a year ago.

Any plans to remove the dependency of graphql-middleware or any current ways to use without?

**Comment by BigsonLvrocha** [comment]
One way to remove the use of graphql-middleware is to directly use `rule.resolve.bind(rule)(resolver, parent, args, ctx, info)` for the field resolvers. it's just required to add `{ _shield: { cache: {} } }` to the context

**Comment by abenhamdine** [comment]
> One way to remove the use of graphql-middleware is to directly use `rule.resolve.bind(rule)(resolver, parent, args, ctx, info)` for the field resolvers. it's just required to add `{ _shield: { cache: {} } }` to the context

thx !
but how do you apply this code on resolvers ?
Could you paste an example ?

**Comment by maticzav** [comment]
Hi everyone!

Thank you for opening this issue. I saw the notice in the `graphql-middleware` page as I was one of the maintainers there as well. I've been planning to diverge from `graphql-middleware` for quite a while since it would let us do many more things with this library.

I'd love to update the library and introduce a couple of new features that many people requested through time. 

The major problem right now is funding and interest. This library used to be funded by GraphCMS, and I used to be a lot more interested in the GraphQL backend, especially because it felt like more people wanted to contribute. 

After it lost funding, I lost a bit of interest in developing it, and Prisma switched heavily to developing GraphQL Nexus, which I thought would deter many people from using it. I can see now that many more people use it than I anticipated. 

I would hope that we could collectively get this project about ~300$/month funding and I could spend more time working on it every month. It feels relevant to mention that funding brings funds as well as (and more importantly) faith in the future of the library. This is due to a sense of the real-world value of the library as companies usually have the funds to support the projects they use and gives feedback that companies will rely on the library for some time.

To conclude, this library needs funds and conversation. I love creating projects for the sake of making projects people use; I just don't want to do it alone.

**Comment by BigsonLvrocha** [comment]
hey @maticzav I've been also planning on continuing improving graphql-middleware, I've studied a long time and managed to accomplish the imutability that people were asking, and update to graphql 5.
Later I'll do a fork of the library project and will be happy to help contributing with code to the library

**Comment by BigsonLvrocha** [comment]
I've managed to upgrade `graphql-middleware` in [my fork](https://github.com/BigsonLvrocha/graphql-middleware), changed the name to `graphql-middleware-tool` so I can [publish to npm right away](https://www.npmjs.com/package/graphql-middleware-tool).
Most of my projects really depend on graphql-shield and graphql-middleware so I'm more than happy to contribute and help keep the library up to date

**Comment by sibelius** [comment]
can you add @BigsonLvrocha to the contributors so he can keep maintaining it? so we don't have to deal with forks?

**Comment by maticzav** [comment]
@BigsonLvrocha very happy to hear that! My suggestion would be to try the maintenance practice with a couple of PRs first, and then I could add you as a contributor. How does that sound? I think we can do the same thing with `graphql-middleware`

**Comment by BigsonLvrocha** [comment]
That sounds great, Ive only had time to address that now, so will do some prs shortly

**Comment by DavidMulder0** [comment]
@maticzav I can sadly offer neither money nor help maintaining, but did want to express my admiration for your work so far. Doing a small freelance project on the side and after too long getting to pick my own full stack... and from my initial experimentation this library is offering one of the cleanest authorization layers I have ever seen. So I know words hold little value, but: Thank you.

**Comment by maticzav** [comment]
@DavidMulder0 that helps some as well 😄 

I think this issue is resolved now as we were able to get `graphql-middleware` back on track (special thanks to @BigsonLvrocha). I have to try a couple of strategies to get some funding for `graphql-shield`, and hopefully, we can rejuvenate it as well.

**Comment by benjamin-rood** [comment]
Thanks for finally marking `graphql-shield` as unmaintained also, and directing us to alternatives. It's the responsible thing to do, and genuinely appreciated.
