### ISSUE TITLE
Can't handle mixed query

### ISSUE THREAD

**Issue by roytan883** [maticzav/graphql-shield#109]
code like this:
```js
const isAuthenticated = rule()(async (parent, args, ctx, info) => {
  console.log("call isAuthenticated args = ", args)
  return true
})
const permissions = shield({
  Query: {
    feed: isAuthenticated,
    post: isAuthenticated,
  },
})
```
If the `query` like this, the `isAuthenticated` only be called once !!!
```
query{
  feed{
    id
    text
  }
  post(id:"cjk9uyalu00110803ow0wrxwm"){
    id
    title
  }
}
```

**Comment by roytan883** [comment]
if i change the auth function name, you should understand:
```js
const canGetFeed = rule()(async (parent, args, ctx, info) => {
  console.log("call canGetFeed")
  return true
})
const canGetPost = rule()(async (parent, args, ctx, info) => {
  console.log("call canGetPost")
  return false
})
const permissions = shield({
  Query: {
    feed: canGetFeed,
    post: canGetPost,
  },
})
```
Expect `feed` and `post` use different auth function. But the result is `ONLY` `canGetFeed ` was called

**Comment by maticzav** [comment]
Hmm, ok. That is indeed an interesting situation. Let me explain how `shield` works; by default, every function is `contextually` cached. This means that regardless of `parent` or `arguments` function result caches and will be reused wherever the same rule is applied in a particular call. 

Could you provide the actual code that you are using? That would help a lot.

Besides that, I recommend you check out the `cache` section of README. Maybe this could solve your problem. Otherwise I’ll help you get through the issue differently. 

https://github.com/maticzav/graphql-shield/blob/master/README.md#cache

**Comment by maticzav** [comment]
Hey @roytan883 have you made any progress on this? 🙂
