### ISSUE TITLE
Fine-grained permission control?

### ISSUE THREAD

**Issue by viztor** [maticzav/graphql-shield#110]
I'm wondering if it's possible to return different result for different users.
for example, i want to only permit users to see the posts they've created themselves. Should this be managed and can this be managed by graphql-shield?

Many thanks.

**Comment by maticzav** [comment]
Hey hey @viztor 👋,

Great question. Would you mind telling me if you're using Prisma by chance? This way I can fine grain the answer.

**Comment by viztor** [comment]
@maticzav thank you for the response. 
Yeah I'm happily embracing Prisma at the moment!

**Comment by viztor** [comment]
Thank you so much for the help! Only started trying GraphQL+prisma+Apollo few days ago, I was just evaluating permission control with shield or custom directive. 

This looks amazing. 🎉

Should've probably checked docs for graphql-middleware. Didn't realize that `parent` was referring to the result from parent query. (resolver function's parent was replaced with an _ in prisma docs)

Therefore, Is it correct to say that rule()() takes a function has the same signature as the resolver function in apollo and returns a Boolean indicating whether the field is accessible?

Maybe you want to add this example to the docs?

Furthermore, In a situation we only want to show the last four digit of phone number for verification purposes. Can it be done with shield? Guessing that is probably the right place for custom directives.

Can't say how much I appreciate the help <3.

**Comment by maticzav** [comment]
Hey, excuse me for a bit delayed response. 

> Therefore, Is it correct to say that rule()() takes a function has the same signature as the resolver function in apollo and returns a Boolean indicating whether the field is accessible?

Indeed, that is the spec currently. I'll add it to the docs, thought it's clear enough from the signature itself.

> Furthermore, In a situation we only want to show, say the last four digit of phone number for verification purposes. Can it be done with shield? Guessing that is probably a right place for custom directives.

I would say neither of them is the right approach to limit digits. I believe this is your business logic and probably one-field specific. Because of that, I would recommend you put the functionality in the resolver.

Even better, just got an idea now, make a new field named `last4digits` alongside other fields of the card. This way you reduce complexity and ease your work regarding security - make one "publicly" accessible and hide the others to account owners.

**Comment by viztor** [comment]
@maticzav 

Yeah, it is indeed clear enough from the function signature. I got confused initially because other use-cases I've encountered before does not need `parent`, and shield is kind of the first package I run into that `parent` prove to be useful.

To use different field for masked data is really a brilliant 🎉 idea! Looking forward to put that into practice.

Thanks!
