### ISSUE TITLE
Is there a "shield way" to make sure current user is creator for update request?

### ISSUE THREAD

**Issue by Strernd** [maticzav/graphql-shield#125]
Let's assume I have Users and Posts, and want to create a UpdatePost mutation and also want to make sure, that only the creator of the post can edit it. I could take the userid from the context (which comes from token auth) and match it with the authorId. But is there a more elegant way to do this via a middleware with graphql-shield?

**Comment by Strernd** [comment]
Ah, I didn't had in mind, that I do have the args parameter in my permission functions.


`const isCreator = rule()(async (parent, args, ctx, info) => {
    return ctx.user && ctx.user.userId === args.creator;
})`

should do the trick.

Maybe it's time to add a tutorial and patterns section? :)

**Comment by Strernd** [comment]
It doesn't do the trick, since it doesn't make sense to submit the creator in the args of an updatePost request. So the questions remains.

**Comment by maticzav** [comment]
Hey @Strernd 👋

That’s an interesting question. I would usually tackle it by checking relation on the database before executing the request. What I mean with this is;

1. We know the `id` of the `Post`
1. We can derive author `id` from `context`, as you already pointed out
1. We can check on the database whether an instance with such `id` and `author` exists. If it does, we allow the mutation, otherwise we prevent it.

I don’t think there’s a clearer way to achieve such functionality as you have to make a database connection at least once to ensure relation exists. 

I hope this gives you some leads, let me know if you need any help implementing it 🙂

**Comment by Strernd** [comment]
`const isCreator = rule()(async (parent, args, ctx, info) => {
    return ctx.prisma.exists.Post({id: args.postId, creator: {id : ctx.user.userId}})
})`

This is what I ended up with, seems to work, besides the fact, that for example deleting an already deleted post will throw an unauthorized error.

**Comment by maticzav** [comment]
So happy to hear it worked! I encourage you to check out #119 as well. It should solve the “wrong error” problem you have now. 

Atop of that, we’ll be releasing a crazy amount of articles, documenation and receipes to make sure everyone can get the best out of `shield` and your input in thread would be super helpful.

Let me know if you could contribute in any way!
