### ISSUE TITLE
Rationale

### ISSUE THREAD

**Issue by Offirmo** [maticzav/graphql-shield#13]
Hi,

I fail to understand what is the use of your project. Is it some kind of firewall?

Could you give an example of what it protects from?

Thanks.

**Comment by maticzav** [comment]
Hey @Offirmo 👋 

Great question! The purpose of `graphql-shield` is to ease the development of permission layer in your GraphQL server. As you've mentioned, it might as well be interpreted as some kind of a firewall. GraphQL Shield is particularly useful when permitting ceratin functionality to authenticated users only for example. I recommend you take a look at the examples in the `examples` folder. 

https://github.com/maticzav/graphql-shield/tree/master/examples

The idea behind GraphQL Shield is the abstraction of `permission` layer and ease of reuse of your permission queries. All of the functionality can be achieved without using GraphQL Shield, but I found myself repeating over and over again when doing it manually - that's why I created `graphql-shield`.

So, to answer your question, `graphql-shield` protects your server from unwanted access. Thanks for pointing out the lack of understanding, I will try to find a better description. I hope I answered your question, but feel free to ask some more 🙂

**Comment by Offirmo** [comment]
Great! Just add this to the README now ;)

**Comment by picosam** [comment]
Hello @maticzav -- may I add that `graphql-shield` serves Authorization requirements of a GraphQL server (vs. Authentication)?

**Comment by maticzav** [comment]
@Offirmo I just update the description. @picosam thanks for pointing this out 🙂
