### ISSUE TITLE
Conflict between options `debug`, `fallback` and `allowExternalErrors`

### ISSUE THREAD

**Issue by johannpinson** [maticzav/graphql-shield#149]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Hey @maticzav 
I have tests some config, and it's seems there is some conflicts between `debug`, `fallback` and `allowExternalErrors`.

In my config, I just put `allowExternalErrors` to true (like in my previous settings in the v2)
The bug is here:
https://github.com/maticzav/graphql-shield/blob/eb333b85db36afff5729e37553985f213f8513e4/src/rules.ts#L69-L73

The problem is that the `try/catch` is managed here by the `options.debug`, why?

## Example rule
```ts
const authRule = rule()(async (parent, args, ctx: Context) => {
  const user = ctx.user
  if (!user || !user.id) {
    throw new MyAwesomeAuthenticationError()
  }
  return true
})

shield({
  Query: {
    me: authRule
  }
}, {
  allowExternalErrors: true
}
```

## Expected behavior

Receive a custom error like `Not Authenticated` or `You're not allowed` etc.

## Actual behaviour

I always receive the default fallback error `Not Authorised!`.

**Comment by maticzav** [comment]
Hey @johannpinson 👋,

Thanks for opening up the issue. I can see why this seems a bit odd since it took me quite some time to align everything in my mind map as well. I was considering the options briefly like this;

If we take a barebones example with `shield`, the application consists of a business logic layer and permission layer. Now, our application seemingly works correctly, and we are ready to push it to production. However, permission layer has a bug and exposing it could potentially lead to data leaks. Since the new version of `shield` allows the use of custom errors, every other mistake that occurs we should treat as a bug since it doesn't follow the prescription. This way we make sure that permission layer itself is secure.

The `allowExternalErrors` option is, in this case,  meant for users who want to forward errors thrown by resolvers - their business logic. I think of `graphql-shield` as a Plug'n'Play solution for GraphQL servers' security. In that respect, I believe we should by default "hide" everything and make it possible for advanced users to modify the settings as they demand.

https://github.com/maticzav/graphql-shield/blob/eb333b85db36afff5729e37553985f213f8513e4/src/generator.ts#L40-L59

`debug` option, on the other hand, throws every error that occurred during execution. This way, it is possible for developers to get an introspection view of their permission system while in development. If there were no such option, it would be significantly harder to track down errors in permission logic.

I hope this gives a better idea of the design choice that I made. 🙂

**Comment by johannpinson** [comment]
Hello @maticzav 

Okay I understand the logic, but btw, how can I define two differrents fallbacks to distinguish an "Authentication" error from an "Authorization" error if I can't throw these errors from the middleware resolver?

**Comment by johannpinson** [comment]
On the other hand, I made some test, an replacing `throw new MyCustomError()` bu `*return* new MyCustomError()`, allow me to get my custom error, even with the default settings.

https://github.com/maticzav/graphql-shield/blob/4268a7784722ba6d5ccdc970675f17e187559552/src/rules.ts#L61-L63

Maybe it needs here to `throw` it instead of `return`.

**Comment by maticzav** [comment]
1) Shield is Authorization library, not primarily Authentication one. You can still use it in that manner though.
2) I don’t understand what you mean with two fallbacks.
3) No, I think it should `return` this way error is passed to GraphQL but isn’t printed as a log.

**Comment by johannpinson** [comment]
Hey!
As discussed together, I understand better the difference between "returning" and "rejecting" eventual errors between an rule and the middleware function.
All is good for me, I close the issue 👍
