### ISSUE TITLE
Updating "context" on the permission layer

### ISSUE THREAD

**Issue by jhnferraris** [maticzav/graphql-shield#16]
Thank you for this helpful tool!

I am just curious are we allowed by shield principle to update the "context" object from the permissions layer then passing it to the resolvers?

**Comment by maticzav** [comment]
@jhnferraris thanks! 

Updating the `context` from `permissions` is possible because `graphql-shield` doesn't copy the context into permission resolve but rather only creates a pointer. I wouldn't recommend doing this, though, because updating the `context` from your permission would only cause blurred separation between logic and permissions, and difficulties with debugging. 

Hope this answers your question 🙂

**Comment by jhnferraris** [comment]
Thanks for answering 👍 

Maybe you can give me some pointers on my use case. Since I want to verify an authorization header, I need to pass around the `user` context after it has been verified in the permission layer. So there will be some 

```

ctx.user = <some user object>

```

before returning a boolean true in the permissions resolver.

**Comment by maticzav** [comment]
@jhnferraris I think you have two options; first, you could create a helper tool which extracts your `userId` from `JWT`, I suppose, or something similar, and then reuse it in every resolver. `graphql-shield` would then help you verify that user exists in the database, for example. 

```ts
const resolver = (parent, args, ctx, info) => {
  const userId = getUserId(ctx)
  return 'something'
}

const permission = (parent, args, ctx, info) => {
  const userId = getUserId(ctx)
  return checkDatabaseForUser(userId)
}
```

The second option is to resolve `user` when creating `context` itself. Using `graphql-yoga` you would achieve this like this: 

```ts
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  context: req => ({
    ...req,
    user: getUser(req),
  }),
})
```

I hope you get the idea 🙂
