### ISSUE TITLE
Is possible to apply a rule to every resolver?

### ISSUE THREAD

**Issue by ellipticaldoor** [maticzav/graphql-shield#167]
# Question about GraphQL Shield

I have to check that a certain custom header is present in every request.

Can I apply a rule to every resolver even if it's not defined on the shield object?

**Comment by ellipticaldoor** [comment]
Awesome! @maticzav thank you :)

**Comment by ellipticaldoor** [comment]
Can I apply a rule by default and specify some exceptions?

I want to make everything to require being authenticated except the login and the signup.

**Comment by ellipticaldoor** [comment]
What if I already have some rules like this?

``` js
const permissions = shield({
  Query: {
    users: or(isAdmin, isEditor),
  },
  Mutation: {
    createBlogPost: or(isAdmin, and(isOwner, isEditor)),
  },
  User: {
    secret: isOwner,
  },
})
```

How I can your checkHeader rule if Im already passing an object with rules?

**Comment by maticzav** [comment]
Hmm, that's an interesting question.

First, the previous question; right now there's no way of achieving such functionality. I believe this is also a very particular scenario; therefore, it wouldn't make sense to change the API to reflect it. Additionally, it conceals the complexity of the permission system which I believe is an anti-pattern once your application grows, or is maintained by multiple developers. From my experience having a complicated default option usually results in little hacks as the app size increases which eventually results in unexpected errors.

Regarding the second question, you could use logic rules, or even simpler have two permission layers. Nevertheless, since your entire app relies on a particular header, you could also check for the header in Express itself - as an Express middleware, and, I believe, slightly increase performance. I think the performance would be most significantly increased in cases when the header is missing since entire request wouldn't even reach GraphQL parsing layer.

**Comment by ellipticaldoor** [comment]
Okay! Thanks :)

**Comment by dlerman2** [comment]
Hi - for what it's worth, I landed here looking for a solution to the same use case -- I want to require auth on every selector except login -- so I don't think it's that unusual. Without a good workaround, I think I'm going to have use a different library which is a shame since I otherwise really like shield!

I agree that having defaults that are overridable adds some complexity, but could you manage it cleanly by having a default selector in the permissions map, eg:

`
{
  Mutation: {
    login: allow,
    _default: isAuthenticated
  }
}
`

where the _default rule gets applied if there are no more explicit matches?

**Comment by ellipticaldoor** [comment]
@maticzav I will like to participate on that, I have a rough idea of how to make it work.

Should I reopen this issue?

**Comment by maticzav** [comment]
Fantastic, I think it would be best if we created another issue for the sake of not mingling this particular issue with our discussion. We could, however, reference it in here afterwards.

It would be beneficial if you could describe the idea and how it moulds into the current API in a new issue where we can discuss the best implementation before its implementation.

**Comment by dlerman2** [comment]
Hi all, happy to chip in. @ellipticaldoor, if you want to create the new feature issue and describe what you're thinking, just add me on the issue and I'll chime in and help where I can!
