### ISSUE TITLE
Error thrown in rules causes "Not Authorised!"

### ISSUE THREAD

**Issue by GRardB** [maticzav/graphql-shield#220]
Hey, super quick question. The code:

```
export const ownsExpense = rule()(async (expense, args, ctx) => {
  const id = (expense && expense.id) || args.id

  // graphql-shield oddity: If an error gets thrown in here,
  // it'll tell the user that they're not authorized, even if
  // that's not the error. If we don't find an expense, we
  // will just make sure the user is logged in. If they are,
  // then we say they "own" the non-existent expense and let
  // the later error get triggered for a better error message
  try {
    const user = await ctx.dbClient.expense({ id }).user()
    const userId = await user.id

    return userId == ctx.user.id
  } catch (e) {
    return !!ctx.user
  }
})
```

Basically, what I want to happen is this: when a user tries to delete a non-existent `Expense`, I want the API to return an error such as:

```
No Node for the model Expense with value cjpq4055shxrk0a42trnn9sb7 for id found
```

With the above code, this happens. Without the try/catch block, however, the error message is:

```
Not Authorised!
```

I've run into this a number of times when implementing things and it makes it pretty difficult to debug other problems in the code. It's also not technically correct. Am I doing something wrong? I'd prefer the code to look more like this:

```
export const ownsExpense = rule()(async (expense, args, ctx) => {
  const id = (expense && expense.id) || args.id
  const user = await ctx.dbClient.expense({ id }).user()
  const userId = await user.id

  return userId == ctx.user.id
})
```

It's much cleaner, easier to understand, and less prone to weird bugs.

Thanks!

**Comment by maticzav** [comment]
Hey @GRardB 👋,

Have you considered using `$exists` query? I believe it should help you with making your code look prettier, more similar to the example you provided.

Furthermore, I suggest you try using `debug` mode in development because it handles the thrown errors a bit differently compared to the `non-debug` mode. You should be able to find the nucleus of the problem a lot more quickly 🙂.

Besides that,`shield` attempts to prevent any cases which could expose the internal structure of the server. Consequentially, we replace all internal errors with default fallback error or specific rule error. For advanced users, however, there's a `allowExternalErrors` option which allows you to control the forwarding of internal errors, but I would advise against using it.

As a rule of thumb, don't rely on errors. Even though JS/TS is very limiting in model expression design, I suggest you use complex structures instead of throwing errors. Code which throws little errors is far more testable and scalable.

**Comment by GRardB** [comment]
Ah, `$exists` is a much better solution! I didn't know that was a thing. Thank you!

In hindsight, it totally doesn't make a lot of sense for an error to bypass the permission-checking. That could definitely leads to security vulnerabilities 😬

Thanks again for your help! I really appreciate it. Consider this issue closed ✅

**Comment by nuronbeck** [comment]
This solution fixed my problem:

`const permissions = shield(
  {
    Query: {},
    Mutation: {}
  },
  {
    allowExternalErrors: true
  }
);`
