### ISSUE TITLE
How to pass data from a rule to a resolver?

### ISSUE THREAD

**Issue by faurehu** [maticzav/graphql-shield#230]
I am attempting to have the rule pass data to the resolver so that I can avoid querying my database twice. I have attempted writing this data on the context object but this will make the response be Not Authorised.

My case is currently very simple. I'm using a rule called `isAuthenticated` which attempts to fetch an user from the database. If this is possible then the rule returns `true` and the resolver is called, however, the resolver will need the user object again and it has to query the database once again.

I am not sure if the prisma object is smart enough to cache the answers per request, but even then it would be helpful to pass data so that I can avoid duplicating lines of code.

**Comment by maticzav** [comment]
Hey @faurehu 👋,

That's an interesting question. I am a firm believer that business logic should entirely be separated from security. I believe this for two reasons; firstly, the code is more scalable because permission rules are better composed and allow broader reusability, and secondly, we can test the system more efficiently.

From my experience, `prisma-binding` uses a very primitive `cache`, however, don't take my word for it. Besides that, I suggest you use `exists` query in permissions schema, and later on actual `user` fetch - makes the code coherent. 

I hope this helps you with your issue. 🙂

**Comment by faurehu** [comment]
Fair enough, this wasn't a feature request but an inquiry trying to discover a solution I was not aware of. Your `exists` suggestion will do for now and I'll take any questions about the prisma `cache` to their team. Many thanks.
