### ISSUE TITLE
Nested Query permissions

### ISSUE THREAD

**Issue by jurajkrivda** [maticzav/graphql-shield#248]
Hello. I have a simple schema with Product, Comment and User types.

```
type Product {
  id: ID!
  name: String!
  comments: [Comment]
}

type Comment {
  id: ID!
  content: String!
  user: User!
}

type User {
  id: ID!
  email: String!
}
```

For a certain product I want to return:
1. all comments if I am admin user 
OR
2. only my comments I am not admin user

My Query: 

```
{
  product(id: 123) {
    id
    name
    comments {
      id
      content
      user {
        id
        email
      }
    }
  }
}
```

How can do this with this great repo.

**Comment by maticzav** [comment]
Hey @jurajkrivda 👋,

Thank you for the kind words! Unfortunately, GraphQL Shield doesn't provide such functionality. The reason for this is that I believe permissions should be entirely separated from business logic. In your case, however, permissions would intervene with the business logic.

We could create an "unsafe" option, but I am not sure whether this would lead to the desired destination. Perhaps you have a take on that?

I hope I helped you with your question. 🙂

**Comment by jurajkrivda** [comment]
Thank you

**Comment by ltamrazov** [comment]
Hi @maticzav , I wanted to follow up on this, since this is also a use case important to us. I was reviewing some of the older issues and ran into: https://github.com/maticzav/graphql-shield/issues/55#issuecomment-395965266

I'm a bit confused, since in ^ you seem to suggest that it IS possible to create rules on nested types?
