### ISSUE TITLE
Yup string transformations are not forwarded

### ISSUE THREAD

**Issue by janwo** [maticzav/graphql-shield#316]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Transformations made with yup inside `inputRole` are not forwarded.

## To Reproduce
```ts
const permissions = shield({
  Query: {
  },
  Mutation: {
      addUser: inputRule( yup => yup.object({
          name: yup.string().lowercase()
      }))
  }
})
```

## Expected behavior

GraphQL should save the user with a lowercased name, even when we run this mutation with uppercased characters.

## Actual behaviour

If you run this mutation with an uppercased name, GraphQL returns a user with that uppercased name.

**Comment by maticzav** [comment]
Hey @janwo 👋,

I have given this a lot of thought over the past couple of days and here's what I've thought of so far. At first sight, having Yup transformations forwarded to your resolvers seems like a dream come true. It does, genuinely. When I first saw your issue, I started working on the fix right away because it sounded fantastic. Nevertheless, after struggling with "fixing" it and thinking about the downsides it brings along, I believe we are not _there_ yet.

The initial motto of GraphQL Shield is that it doesn't interfere with your business logic. I believe this is crucial for two reasons; 1) It makes testing your applications a lot easier; 2) there's a single source of truth.

I haven't yet stumbled upon a project which would significantly benefit from such functionality in the long run, and it doesn't prove very beneficial either to me or people who are backing this project.

Taking into account the increase in feature requests for a rule type that would support side-effects, I am considering creating a new, `effect` rule which would differentiate from other rules by forwarding side effects to the resolvers. That's where we could implement such side-effect-agnostic-validation types.

I would be willing to start working on it in case enough people back this project and explain why this is important to them sooner, otherwise, I will probably leave it until I found a situation where my project would benefit from such functionality.

> PS.: PRs are very welcome 🙂

**Comment by P4sca1** [comment]
Imo the `inputRule` should not alter the `args` object.
Why would you need such a feature?
The `args` object already gets transformed to the correct scalar type by the graphql server, because the types are specified in the schema. So a number is already a number and a boolean is already a boolean. If you need further transformation this should be done in a custom rule I think.
