### ISSUE TITLE
Only single validation sent to client at a time

### ISSUE THREAD

**Issue by marbemac** [maticzav/graphql-shield#323]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Note: not sure if this is a bug or working as intended.

Consider a validation like this:

```ts
inputRule((yup) => {
  return yup.object({
    email: yup.required(),
    username: yup.required(),
    password: yup.required(),
  })
})
```

If I invoke the graphql mutation that uses this yup validation, with no input arguments, I will only see one validation error at a time. This makes it difficult to build a nice user experience on things like login forms, etc, since the user will only see one issue at a time.

## Expected behavior

I expect the graphql api to return three validations, ideally with the path to the property associated with each validation error. Something along the lines of "email is required", "username is required", and "password is required".

## Actual behaviour

Only one validation at a time is returned.

## Additional context

This behavior can be controlled on the `yup` side of things via the `abortEarly` validation option, e.g. `yup.validate(schema, { abortEarly: false })`.

**Comment by P4sca1** [comment]
I would also prefer if `abortEarly` was set to `true` by default.

**Comment by maticzav** [comment]
Hey :wave:,

Excuse my absence, I had my final examinations, but I am up and running now. I have done some experimentation and I propose the following. `inputRule` should be extended so that it exposes `options` which will include all available Yup options.

Furthermore, we should somehow enable the possibility of manipulating the errors list returned by Yup since I cannot find a better default alternative. I have attached an example of error object and its complement on GraphQL side below so you get the idea of the data that we are dealing with.

```ts
ValidationError {
      name: 'ValidationError',
      value: { email: 'notemail' },
      path: undefined,
      type: undefined,
      errors: [ 'It has to be an email!', 'password is a required field' ],
      inner:
       [ ValidationError {
           name: 'ValidationError',
           value: 'notemail',
           path: 'email',
           type: undefined,
           errors: [Array],
           inner: [],
           message: 'It has to be an email!',
           params: [Object] },
         ValidationError {
           name: 'ValidationError',
           value: undefined,
           path: 'password',
           type: 'required',
           errors: [Array],
           inner: [],
           message: 'password is a required field',
           params: [Object] } ],
      message: '2 errors occurred' }

GraphQLError {
           message: '2 errors occurred',
           locations: [Array],
           path: [Array] } ]
```

Perhaps you have any idea how we could make this more approachable?
