### ISSUE TITLE
Customize cache key function

### ISSUE THREAD

**Issue by KATT** [maticzav/graphql-shield#347]
# Feature request

## Is your feature request related to a problem? Please describe

The current `hash()` function doesn't work for all objects. In my case I have instances of [sequelize](https://github.com/sequelize/sequelize) models which causes `hash()` to crash when using `cache: 'strict'`.

## Describe the solution you'd like

Customize the generateCacheKey

## Describe alternatives you've considered

Submitting issue or fixing the hash library

**Comment by P4sca1** [comment]
Just spent hours of debugging why I am always getting the fallback error and finally found out that it it because I am using `cache: 'strict'`.
Noticed this issue and it is indeed the case, that the `hash` function crashes for some objects causing the `fallbackError` to always be displayed without further notice.
In my case the `parent` is a `TypeORM` entity.
Would be great if such errors would be shown and not just hidden away, because otherwise this is a pain to debug. @maticzav 
Also there should be instructions on how to setup a custom `generateCacheKey` function on a per rule basis or we should find out why the `hash` function crashes.

**Comment by KATT** [comment]
@P4sca1 

- To address the debugging nightmare I created PR #350
- For specifying your own `generateCacheKey` I did #348 & #351

**Comment by P4sca1** [comment]
@maticzav @KATT How about replacing the `debug` option with the popular [debug package](https://github.com/visionmedia/debug) or at least use both things in parallel?
At least for me that would've made the process of finding the issue much easier, because my `DEBUG=*` logger (which I always run in dev) would've logged an error.

**Comment by maticzav** [comment]
@P4sca1 `debug` sounds great. Could you create a PR? I'll merge it right away.

@KATT I'll merge your PRs in the upcoming days.
