### ISSUE TITLE
Rules with parameters

### ISSUE THREAD

**Issue by peterrogov** [maticzav/graphql-shield#385]
Is there a way to have a rule with some input arguments? 

I am trying to make a rule like this:
```
const hasRole = (roleName: string) =>
    rule(`userHasRole-${roleName}`)(
        async (parent, args, ctx, info) => {
            return (ctx.user && ctx.user.role === roleName);
        }
    );
```

And then use it in this way:
```
Mutation: {
    createUser: and(user.hasRole("admin"), input.createUser),
},
```
And this gives me a run-time error:
> Error: There seem to be multiple definitions of these rules: userHasRole-admin

I understand that this is exactly what is explained in the documentation. However my question remains, is there a way to have such rules with `graphql-shield`? I want to use rules for different claims that may be issued to a user. The total number of claims may be quite big and I don't really want to define a separate function for every claim/role that may exist.

**Comment by maticzav** [comment]
Hey 👋 ,

That's a fascinating question. Could you try creating role-specific rules before assigning them to the rule tree? Something like that:

```ts
const hasRole = (roleName: string) =>
    rule(`userHasRole-${roleName}`)(
        async (parent, args, ctx, info) => {
            return (ctx.user && ctx.user.role === roleName);
        }
    );

const hasAdminRole = hasRole("admin")
const hadUserRole = hasRole("user")

const permissions = shield({
  Query: {
    user: hasUserRole,
    admin: hasAdminRole,
  },
 Mutation: {
   createUser: hasAdminRole,
  }
})
```

What the error is saying is that you are trying to use two different rules with the same name (because you create multiple instances). Let me know if that worked; otherwise, we'll try something new 😄

**Comment by peterrogov** [comment]
@maticzav thanks for your response! I somehow didn't think of this part from your answer which I believe should work for me
```
const hasAdminRole = hasRole("admin")
const hadUserRole = hasRole("user")
```
Will try it out and revert

**Comment by maticzav** [comment]
Awesome! Let me know how it went. Besides, do you think the error message should be more descriptive?

**Comment by peterrogov** [comment]
So the code I had after posting this issue and before your response was like this:
```
const userHasRole = (user: any, roleName: string) => {
    if (user && user.role === roleName) {
        return true;
    } else {
        return new ForbiddenError(`User role is expected: ${roleName}`);
    }
};

const hasRoleAdmin = rule()(async (parent, args, ctx, info) => userHasRole(ctx.user, "admin"));
const hasRoleUser = rule()(async (parent, args, ctx, info) => userHasRole(ctx.user, "user"));
```

Which is basically similar to what you have suggested with the difference in how a rule's name is generated. In my case I leave it to `rule()` function to decide. 

I have tried with your code and it also works fine. So since there's no much difference in behaviour I decided to stick to my existing code (unless there's something I don't understand about how rule names are created and used).

With regard to the error message I believe it is informative enough (especially after you read `graphql-shield`'s README).

**Comment by maticzav** [comment]
@peterrogov I couldn't agree more with you! I think you wrapped the issue very well together. My last point, perhaps, as you asked; I don't think there should be an enormous performance spike in case you use either of the two approaches. Nevertheless, it's worth noting that the idea behind logic rules stems from situations like yours, where rules that are used in unison with others or alone always employ the most performant calculation approach because they need only be calculated once. Therefore, if you construct multiple rules, that could be further separated and reused, it is possible that calculations overlap and produce a performance overhead.

With that in mind, I believe GraphQL Shield finally features a nearly complete set of tools that you can use to achieve the same step-by-step functionality and custom error messages that you used in your concocted rule. For that, I encourage you to check out the `chain` rule and `CustomError`. To give you an example of what I have in mind;

```ts
const isAuthenticated = rule()(() => {
  if(!ctx.user || !isAuthenticated(ctx.user)){
    return new AuthenticationError("Authentication required");
  }
  return true
})

const isAdmin = rule()(() => {
  if(ctx.user.role !== "admin" && ctx.user.role !== "manager"){
    return new ForbiddenError("User has no right to access this data");
  }
  return true
})

...

const permissions = shield({
  Query: {
    session: isAuthenticated,
    user: chain(isAuthenticated, and(or(hasUserRole, hasManagerRole), canAccessUsers)),
    allUsers: chain(isAuthenticated, hasManagerRole)
  }
})
```

```gql
query {
  session { id name }
  user(id: "123") { name company }
  allUsers {
    id
    name
    email
  }
}
```

Let me know if that's what you had in mind :slightly_smiling_face:.

> P.S.: I just noticed that you are already using custom rules but thought it might be useful if someone with a similar issue comes across the thread.

**Comment by peterrogov** [comment]
@maticzav Thanks for the feedback. I believe we're on the same page and I have got the answers to my questions, your help is very much appreciated! 

How's `chain` different from `and` by the way? I'd assume that `chain` validates all rules in that exact order as they are given in the code but I'm not sure.

**Comment by peterrogov** [comment]
@maticzav sorry, I see there's a section about `chain` in README. Great stuff, it does address mostly my initial issue and I agree with you that other `graphql-shield` users should consider using `chain` instead of my approach with complex rule unless they are certain `chain` does not work well for them.

**Comment by maticzav** [comment]
@peterrogov happy to hear that. Thank you for the great thread!

I’ll close the issue as it seems to be resolved but feel free to reopen in case you feel there’s more to it.
