### ISSUE TITLE
More info about caching

### ISSUE THREAD

**Issue by jvbianchi** [maticzav/graphql-shield#7]
How does do cache work?

How long is the cache life cycle? 

Does it create a cache for each request?

Sorry for so many question... Great project!!

**Comment by maticzav** [comment]
Hey @jvbianchi 👋 

You are right, the cache is stored for each request separately. The outcome of each permission function is saved under function's name in the `context` of a resolver - `context` is the only value that is being passed through all the resolvers in the chain.

To use the `cache` you have to use the same function (name) in two different permission levels. 
```ts
// caches
const auth = () => authorise
const permissions = {
   Query: {
      user: auth
   },
   User: {
      secret: auth
   },
}
```

This, for example, wouldn't work, because we have no way of telling how is your `permission` connected with your logic - we need to know the name of the function to make a reference (functions with the same name are considered to do the same thing).
```ts
// doesn't cache
const permissions = {
   Query: {
      user: () => authorise
   },
   User: {
      secret: () => authorise
   },
}
```

**Comment by jvbianchi** [comment]
Oh, now I understand.

I think you could put this info on the readme.
