### ISSUE TITLE
Fully-hydrated User in context

### ISSUE THREAD

**Issue by steida** [maticzav/graphql-shield#76]
I am confused. In examples, there is a fully-hydrated User object. But how we can async fetch it from DB?

**Comment by steida** [comment]
Is this related?

![screen shot 2018-06-20 at 22 28 23](https://user-images.githubusercontent.com/66249/41682872-4e99cad8-74d9-11e8-98df-31c3ba5514fd.png)

https://graphql.org/learn/authorization/

**Comment by maticzav** [comment]
Hey @steida 👋,

That's an interesting question. I would say you have two options when it comes to obtaining user. I would assume that you use `graphql-yoga` or `apollo-server` or something similar, which both lead to `express` implementation of GraphQL. In such scenario, you could resolve the user as another middleware and then access it from the context.

On the other hand, you have the option to use `graphql-middleware`. Instead of adding middleware beforehand, you could resolve user before it reaches your core resolver. Check out [graphql-middleware](https://github.com/prismagraphql/graphql-middleware).

Besides that, `shield` allows you to do anything you could in your "normal" resolver in your rules as well.  Hence, yes, you can fetch user and do DB calls in rules no different.

I hope this sparks some ideas! 🙂 

PS.: I love the idea about `graphql-middleware` plugin which would resolve user. I might give it some more thought. Will keep you posted if anything comes out!

**Comment by steida** [comment]
That's what I am using now. `userId: ?string` seems to be enough for now. Let's see.
Btw, thank you for very interesting lib. Soon it will be used in https://github.com/este/este :-)

```js
const maybeGetUserId = (request) /*: ?string */ => {
  const authorization = request.get('authorization');
  if (!authorization) return null;
  const token = authorization.replace('Bearer ', '');
  const decoded = jsonwebtoken.verify(token, process.env.API_SECRET || '');
  // https://flow.org/en/docs/lang/refinements
  if (decoded == null || typeof decoded.userId !== 'string') return null;
  return decoded.userId;
};

const server = new yoga.GraphQLServer({
  typeDefs: 'server/api/model.graphql',
  resolvers,
  middlewares: [permissions],
  resolverValidationOptions: {
    // https://github.com/prismagraphql/prisma/issues/2225#issuecomment-384697669
    requireResolversForResolveType: false,
  },
  context: context => ({
    ...context,
    db: new prisma.Prisma({
      typeDefs: 'database/schema.graphql',
      endpoint: process.env.PRISMA_ENDPOINT,
      secret: process.env.PRISMA_SECRET,
      // log all GraphQL queries & mutations
      // process.env.NODE_ENV !== 'production'
      debug: false,
    }),
    userId: maybeGetUserId(context.request),
  }),
});
```

**Comment by maticzav** [comment]
Whoa, that's so cool! Let me know if you need anything! 🎉

**Comment by steida** [comment]
The question is whether it's a good pattern to automatically fetch user if a token is passed. If so, then middleware doing that is the right approach. But I am still not convinced we should do that. Why? Because of roles? Anything else?

**Comment by maticzav** [comment]
Hey @steida, sorry for the delay. If I understand you correctly, you want to discuss whether we should pass in fully hydrated user and fetch if beforehand, or pass in the query and wait for the chunk of code which requires user info to do loading itself, correct?

In my opinion, we usually want to possess user information. Therefore, the number of queries which require authentication outnumbers the ones that don't. Because of this, we shouldn't care too much about the minority since it's not going to represent an extreme decay in performance. 

Furthermore, the latency produced by fetching the user once can be neglected since, if we were to load it every time over and over again (assuming we don't integrate caching techniques), the time occupied there would be higher than here.

Because of this two reasons, I usually fetch it beforehand. I typically do it in Express middleware or something similar. 

I hope this answered your question to a certain degree! Nevertheless, I would love to explore cons of such approach and see what indeed works best - since this is only my opinion. 🙂

**Comment by steida** [comment]
Thank you :-)
