### ISSUE TITLE
Using GraphQL Shield with GraphQLSchema object not working

### ISSUE THREAD

**Issue by alyatwa** [maticzav/graphql-shield#764]
I'm trying to use GraphQLSchema object with shield but it does't work  
here is an example
[https://repl.it/@alyatwa/shield](https://repl.it/@alyatwa/shield)

**Comment by maticzav** [comment]
Hey @alyatwa 👋 ,

Thank you for opening this issue. After some investigation, it seems like this is a bug in `graphql-middleware`. Instead of setting up the server with schema returned from `applyMiddleware` return the original schema and apply middleware as an effect

```ts
applyMiddleware(schema, permissions);
```

Let me know if that worked for you as well. 🙂

**Comment by alyatwa** [comment]
It works now!
